### ISSUE TITLE
getTransition error on sdk

### ISSUE THREAD

**Issue by biemond** [thomasletsch/bisecure-gateway#14]
Hi, 

Nice project, I am thinking to use your project as a base for making an athom homey app in node. Great work and lot of respect.

I see this error on startuptest and I hope it helps you to improve the code for all possible combination.

Thanks Edwin

```
Groups: [Group(id=0, name=GARAGE, ports=[Port(id=0, type=4 (UP)), Port(id=1, type=5 (DOWN)), Port(id=2, type=6 (HALF))])]
Sending package command: Command(code=112 (70), name='HM_GET_TRANSITION'), tag: 0, token: 00000000, payload: 00, isResponse=false
Sending transport container 000000000000801F120B2768000A000000000070007ABB
Received from socket: 801F120B2768000000000006000A0000000000010C17BE
Received: sender: 801F120B2768, receiver: 000000000006, pack: command: Command(code=1 (1), name='ERROR'), tag: 0, token: 00000000, error: PERMISSION_DENIED, isResponse=false, checksum: BE

java.lang.ArrayIndexOutOfBoundsException: 2

	at de.thomasletsch.Transition$Companion.from(Transition.kt:46)
	at de.thomasletsch.ClientAPI.getTransition(ClientAPI.kt:93)
	at de.thomasletsch.Startup.startup(Startup.kt:29)
	at de.thomasletsch.StartupTest.testStartup(StartupTest.kt:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by warting** [comment]
Hi @biemond! I'm glad you found this project. I also had plans for creating a Homey and also an android app, while @thomasletsch planning to create an openHAB app. 

We choose to create this library in kotlin to hopefully be able to compile the library to a jar for the android app, npm for Homey and binary for openHAB

https://kotlinlang.org/docs/tutorials/javascript/kotlin-to-javascript/kotlin-to-javascript.html
https://kotlinlang.org/docs/reference/native-overview.html

We are also looking into to transition this repo to an organization that you maybe can join?

**Comment by biemond** [comment]
awesome, I will support you with this  and test it out on my device

**Comment by biemond** [comment]
![screenshot_2019-02-18-10-11-35](https://user-images.githubusercontent.com/1085004/52940016-cae17f00-3365-11e9-8998-5a3062b6bc66.png)
<img width="1153" alt="screenshot 2019-02-18 at 10 10 35" src="https://user-images.githubusercontent.com/1085004/52940033-d46ae700-3365-11e9-9b48-5cb5c6a8af36.png">

**Comment by biemond** [comment]
thanks, see the above pics. indeed the latest,not approved version  0.0.5 fixes the current power unit issue and with your data I also fixed E-total with the right unit.

thanks for your data , I hope they publish it soon.
